{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-server.fullname" . }}-stable
spec:
  selector:
    app: {{ include "web-server.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-server.fullname" . }}-canary
spec:
  selector:
    app: {{ include "web-server.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-server.fullname" . }}
spec:
  selector:
    app: {{ include "web-server.fullname" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
{{- end }}
