apiVersion: v1
kind: Service
metadata:
  name: warhammer40k10thcalc-web-active
  namespace: default
spec:
  selector:
    app: warhammer40k10thcalc-web
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: warhammer40k10thcalc-web-preview
  namespace: default
spec:
  selector:
    app: warhammer40k10thcalc-web
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP