replicas: 1
rollout:
  enabled: false
analysis:
  enabled: false
ingress:
  host: stage.calc.warhammer40k.ru
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
image:
  repository: ghcr.io/annoname1/warhammer40k10thcalc
  tag: 340481a5fe56a5c8e1fda65afd5e1d2849f752c2
