replicas: 1
rollout:
  enabled: false
analysis:
  enabled: false
ingress:
  host: stage.calc.warhammer40k.ru
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
image:
  repository: ghcr.io/annoname1/warhammer40k10thcalc
  tag: 4ebd38e93f88ced47f1c830b0b62111eccbfcc67
